const { stripHTML } = require(`hexo-util`);

/**
 * @public
 * @function
 * @alias strip_html
 * @desc Strip HTML tags from string <br>
 *  The addition of highlightJS generated line indicator and special character
 *  conversion is different from hexo one.
 * @param {string} str - the original string
 * @return {string}
 * @example
 * p= strip_html(post.content)
 */
function stripHTMLHelper(str) {
  return stripHTML(
    str
      // removing line indicators generated by syntax-highlighter
      .replace(/(<td class="gutter">)[^(td)]*(\/td>)/g, "")
      // converting special characters
      .replace(/&#(\d+);/g, (_, dec) => `${String.fromCharCode(dec)}`)
  );
}

module.exports = stripHTMLHelper;
