const { stripHTML } = require(`hexo-util`);

/**
 * @desc Strip HTML tags from string
 * @param {string} str - the original string
 * @return {string}
 */
function stripHTMLHelper(str) {
  return stripHTML(
    str
      // ensuring whitespace between elements
      .replace(/</g, " <")
      // removing line indicators generated by syntax-highlighter
      .replace(/(<td class="gutter">)[^(td)]*(\/td>)/g, "")
      // converting special characters
      .replace(/&#(\d+);/g, (_, dec) => `${String.fromCharCode(dec)}`)
  );
}

module.exports = stripHTMLHelper;
